config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :ateliers
  get "dashboard", to: "pages#dashboard"

  resources :ateliers do
    resources :reservations, only: [:create, :destroy]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/atelier.rb
class Atelier < ApplicationRecord
  belongs_to :user
  has_many :reservations, dependent: :destroy
  has_many_attached :photos
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :search_by_style,
                  against: [:style],
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :atelier
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :avatar
  has_many :ateliers
  has_many :reservations, through: :ateliers, dependent: :destroy
  has_many :reserved, class_name: :Reservation, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit::Authorization
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone_number, :address, :avatar])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :phone_number, :address, :avatar])
  end
end

private

def skip_pundit?
  devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
end

app/controllers/ateliers_controller.rb
class AteliersController < ApplicationController
  before_action :set_atelier, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @ateliers = policy_scope(Atelier)

    return unless params[:query].present?
    if params[:query][:address].present? && params[:query][:style].present?
      @ateliers = @ateliers.near(params[:query][:address].to_s, 10)
      @ateliers = @ateliers.search_by_style(params[:query][:style])
      @style = params[:query][:style]
      @address = params[:query][:address]
    elsif !params[:query][:address].present? && params[:query][:style].present?
      @ateliers = @ateliers.search_by_style(params[:query][:style])
      @style = params[:query][:style]
    elsif params[:query][:address].present? && !params[:query][:style].present?
      @ateliers = @ateliers.near(params[:query][:address].to_s, 10)
      @address = params[:query][:address]
    end
    @markers = @ateliers.geocoded.map do |atelier|
      {
        lat: atelier.latitude,
        lng: atelier.longitude,
        info_window: render_to_string(partial: "info_window", locals: {atelier: atelier})
      }
    end

  end

  def new
    @atelier = Atelier.new
    authorize @atelier
  end

  def create
    @atelier = Atelier.new(atelier_params)
    @atelier.user = current_user
    @atelier.save
    authorize @atelier
    redirect_to atelier_path(@atelier)
  end

  def show
    @reservation = Reservation.new
    authorize @atelier
  end

  def edit
    authorize @atelier
  end

  def update
    @atelier.update(atelier_params)
    redirect_to dashboard_path(current_user)
    authorize @atelier
  end

  def destroy
    @atelier.destroy
    authorize @atelier
    redirect_to dashboard_path(current_user), status: :see_other
  end

  private

  def set_atelier
    @atelier = Atelier.find(params[:id])
  end

  def atelier_params
    params.require(:atelier).permit(:name, :address, :style, :details, :price_per_day, photos: [])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def dashboard
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def create
    @reservation = Reservation.new(reservation_params)
    skip_authorization
    @atelier = Atelier.find(params[:atelier_id])
    @reservation.atelier = @atelier
    @reservation.user = current_user
    @reservation.save
    redirect_to dashboard_path(current_user)
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    skip_authorization
    @reservation.destroy!
    redirect_to dashboard_path(current_user), status: :see_other
  end

  private

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ateliers/_info_window.html.erb
<% if atelier.photos.attached? %>
  <%= cl_image_tag(atelier.photos.first.key)%>
  <% end %>
<h2><%= atelier.name%></h2>
<p>Prix: <%= atelier.price_per_day%>€/jour</p>

app/views/ateliers/edit.html.erb
<div class="container-formulaire">
<h2>Edit atelier</h2>
  <div class="formulaire">
    <div>
      <%= simple_form_for @atelier do |f| %>
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :style, collection:["Atelier cuisine", "Atelier broderie","Atelier photographie", "Atelier de tissage", "Atelier de cuir", "Atelier de poterie", "Atelier de textile", "Atelier de gravure"]%>
        <%= f.input :details %>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
        <%= f.input :price_per_day %>
        <%= f.button :submit, class: "button" %>
      <% end %>
    </div>
  </div>

</div>

app/views/ateliers/index.html.erb
<div class ="titre text-center">
  <h2><%= @style ? @style : "Tous les ateliers" %> <%= "à #{@address}" if @address %></h2>
  <p><%= pluralize @ateliers.length , 'ateliers'%> </p>
</div>



<%# <div class="container"> %>
<div class="m-3">
  <div class="row">
    <div class="list-cards col-6">
      <% @ateliers.each do |atelier| %>
        <div class ="card">
          <% if atelier.photos.attached? %>
            <%= link_to (cl_image_tag(atelier.photos.first.key,
            width: 400, height: 300, crop: :fill)), atelier_path(atelier) %>
          <% else %>
            <%= link_to (image_tag("https://picsum.photos/400/300",
            width: 400, height: 300, crop: :fill)),  atelier_path(atelier)%>
          <% end %>
          <div class="atelier-info px-4">
            <div class="style-name "><%= link_to atelier.name %>
            </div>
            <div class="style-details"><%= atelier.address %>
            </div>
            <div class="price-left">
              <%= atelier.price_per_day%>€/jour
              <%# <p>
              <%= link_to "Show atelier", atelier_path(atelier) %>
              <%# </p> %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-6">
      <div id="map">
        <div style="width: 100%; height: 100vh;"
          data-controller="map"
          data-map-markers-value="<%= @markers.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    </div>
  </div>
</div>
<%# </div> %>

app/views/ateliers/new.html.erb
<div class="container-formulaire">
  <h2>New atelier</h2>
  <div class="formulaire">
    <div>
      <%= simple_form_for @atelier do |f| %>
        <%= f.input :name %>
        <%= f.input :address,
        input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"}, wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}%>
        <%= f.input :style, collection:["Atelier cuisine", "Atelier broderie","Atelier photographie", "Atelier de tissage", "Atelier de cuir", "Atelier de poterie", "Atelier de textile", "Atelier de gravure"]%>
        <%= f.input :details %>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
        <%= f.input :price_per_day %>
        <%= f.button :submit, class: "button" %>
      <% end %>
    </div>
  </div>
</div>

app/views/ateliers/show.html.erb
<div class="container-atelier">
  <div class= "col-12 col-md-6">
    <div class= "container-details">
      <h1 class="title"><%= @atelier.name %></h1>
      <h5 class = "undertitle"><%= @atelier.style %></h5>
      <p class="texte"><%= @atelier.address %></p>
    </div>

    <div class="container-details w-100">
      <div class="col-12 col-md-6 w-75">
        <h4 class="title">Détails</h4>
        <p class = "texte"><%= @atelier.details %></p>
      </div>
    </div>

        <div class="container-details w-100">
      <div class="col-12 col-md-6 w-75">
        <h5 id= "proprietaire"><%= @atelier.user.first_name %> <%= @atelier.user.last_name %></h5>
        <p class = "texte">Propriétaire </p>
      </div>
    </div>

  </div>

  <div class= "col-12 col-md-6 show_page_">
      <div id="carouselExampleControls" class="carousel slide container-details p-0 mb-4" data-ride="carousel">
          <div class="carousel-inner">
            <% @atelier.photos.each_with_index do |photo, index| %>
              <div class="carousel-item <%= "active" if index == 0 %>">
                <%= cl_image_tag photo.key, class:"d-block w-100" %>
              </div>
            <% end %>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
      </div>

      <div class="card_reservation container-details w-100 mb-3">
          <h4>Prix par jour : <span class="strong"><%= @atelier.price_per_day %>€</span></h4>
            <%= simple_form_for [@atelier, @reservation] do |f| %>
              <%= f.input :start_date%>
              <%= f.input :end_date%>
              <% if @atelier.user == current_user %>
                <%= f.button :submit, class: "button disabled"%>
              <% else %>
                <%= f.button :submit, class: "button"%>
              <% end %>
            <% end %>
      </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workshop</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://unpkg.com/swiper@8/swiper-bundle.min.css"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@600&display=swap" rel="stylesheet">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@1,100&family=Space+Mono&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@100&family=Poppins:ital,wght@1,100&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>

    <script src="https://kit.fontawesome.com/132f91c3ef.js" crossorigin="anonymous"></script>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Abel&family=Josefin+Sans:wght@200&family=Open+Sans:wght@300&family=Pacifico&family=Poppins:ital,wght@1,100&family=Raleway&display=swap" rel="stylesheet">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>  </head>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <div class="content-wrapper">
    <%= yield %>
    </div>
    <div class="footer">
      <div class="footer-copyright">
        Suivez-nous <i class="fas fa-heart"></i>
      </div>
      <div class="footer-links">
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
      </div>
    </div>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container">
  <div class="row">

    <div class="col-sm-12 col-md-6 col-lg-6">
      <div class="profil">
        <% if current_user.avatar.attached? %>
          <%= cl_image_tag(current_user.avatar.key,
          width: 50, height: 50, crop: :fill) %>
          <% else %>
          <%= image_tag("https://picsum.photos/400/300",
          width: 50, height: 50, crop: :fill)%>
        <% end %>
        <h4><%= current_user.first_name %> <%= current_user.last_name %></h4>
        <p>Adresse : <%= current_user.address %></p>
        <p>Numéro de téléphone :<%= current_user.phone_number %></p>
        <p>Email : <%= current_user.email %></p>
      </div>
    </div>

    <div class="col-sm-12 col-md-6 col-lg-6 vos-ateliers">
      <h2>Vos ateliers</h2>
      <div class="ateliers">

        <% current_user.ateliers.each do |atelier| %>
          <div class="atelier">
            <% if atelier.photos.attached? %>
            <%= link_to (cl_image_tag(atelier.photos.first.key,
            width: 200, height: 150, crop: :fill)), atelier_path(atelier.id)  %>
            <% else %>
            <%= link_to (image_tag("https://picsum.photos/400/300",
            width: 200, height: 150, crop: :fill)), atelier_path(atelier.id) %>
            <% end %>
            <h6><%= atelier.name %></h6>
            <p><%= link_to 'Modifier', edit_atelier_path(atelier.id)%></p>
            <p><%= link_to "Supprimer",
            atelier_path(atelier),
            data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
            %></p>
          </div>
        <% end %>
      </div>

      <%= link_to 'Ajouter un atelier', new_atelier_path, class: "btn button" %>
    </div>
  </div>

  <div class="row">

    <div class="col-sm-12 col-md-6 col-lg-6">
      <div class="notifications">
      <h2>Vos notifications:</h2>
        <% current_user.reservations.each do |reservation| %>
          <div class="notification">
            <p><%= "Réservation de #{reservation.user.first_name} #{reservation.user.last_name}" %></p>
            <p><%= "Du #{reservation.start_date} au #{reservation.end_date}" %></p>
            <p><%= reservation.atelier.name %></p>
            <p><%= link_to "Annuler", atelier_reservation_path(reservation.atelier, reservation), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></p>
          </div>
        <% end %>
      </div>
    </div>

    <div class="col-sm-12 col-md-6 col-lg-6">

      <div class="reservations">
      <h2>Vos réservations:</h2>

        <% current_user.reserved.each do |reservation| %>
          <p><span class="atelier-strong"><%= reservation.atelier.name %></span> : <%="du #{reservation.start_date} au #{reservation.end_date}" %>   <%= link_to "Annuler", atelier_reservation_path(reservation.atelier, reservation), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></p>
          <p></p>
        <% end %>
      </div>
    </div>

  </div>


</div>

app/views/pages/home.html.erb
<div class="banner banner-custom" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1595351298020-038700609878?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170);">

    <h1>Louer votre atelier</h1>
    <p>à d’autres professionnels</p>
    <%= simple_form_for :query, url: ateliers_path, wrapper: :inline_form, html: { class: "row row-cols-lg-auto g-3 align-items-center search-input" }, method: "GET" do |f| %>
      <%= f.input :style, label: false, include_blank: "Style d'atelier",
                  collection:["Atelier cuisine", "Atelier broderie","Atelier photographie", "Atelier de tissage", "Atelier de cuir", "Atelier de poterie", "Atelier de textile", "Atelier de gravure"],
                  :input_html => { :class => 'input' }, wrapper_html: { class: "m-0"} %>
      <p class="color-black">Adresse :</p>
      <%= f.input :address,
                  input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
                  wrapper_html: {class: "m-0", data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}} %>
      <div class="col-12">
        <%= button_tag type: "submit" do %>
          <i class="fa-solid fa-magnifying-glass"></i>
        <% end %>
      </div>
    <% end %>
</div>
<br>
<h2 class="josefin">Nos ateliers</h2>
<h2 class="pacifico">à louer</h2>



<div class="swiper mySwiper">
  <div class="swiper-wrapper">
    <% Atelier.all.last(6).each do |atelier| %>
      <div class="swiper-slide">
        <%= link_to atelier_path(atelier) do %>
          <%= cl_image_tag(atelier.photos.first.key) %>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="swiper-pagination"></div>
</div>

    <!-- Swiper JS -->
<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>

    <!-- Initialize Swiper -->
<script>
  var swiper = new Swiper(".mySwiper", {
    effect: "coverflow",
    grabCursor: true,
    centeredSlides: true,
    slidesPerView: "auto",
    coverflowEffect: {
      rotate: 50,
      stretch: 0,
      depth: 100,
      modifier: 1,
      slideShadows: true,
    },
    pagination: {
      el: ".swiper-pagination",
    },
  });
</script>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag("logo.png") %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item active d-flex">
            <%= link_to "Home", root_path, class: "nav-link home" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
          <% if current_user.avatar.attached? %>
            <%= cl_image_tag(current_user.avatar.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
          <% else %>
            <%= image_tag("https://picsum.photos/100/100", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
          </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link home" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>